prooph_event_store:
  stores:
    todo_store:
      event_store: Prooph\EventStore\Pdo\MySqlEventStore
      repositories:
        todo_list:
          repository_class: App\ProophessorDo\Infrastructure\Repository\EventStoreTodoList
          aggregate_type: App\ProophessorDo\Model\Todo\Todo
          aggregate_translator: prooph_event_sourcing.aggregate_translator
          one_stream_per_aggregate: true
          #stream_name: 'user#6'

services:
  Prooph\EventStore\Pdo\MySqlEventStore:
    arguments: ['@prooph_event_store.message_factory', '@doctrine.pdo.connection', '@prooph_event_store.single_stream_strategy']

  doctrine.pdo.connection:
    class: PDO
    factory: ['@database_connection', getWrappedConnection]

  prooph_event_store.single_stream_strategy:
    #class: Prooph\EventStore\Pdo\PersistenceStrategy\MySqlSingleStreamStrategy
    class: Prooph\EventStore\Pdo\PersistenceStrategy\MySqlAggregateStreamStrategy

  prooph_event_sourcing.aggregate_translator:
    class: Prooph\EventSourcing\EventStoreIntegration\AggregateTranslator